# Generated by Django 5.1.4 on 2025-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_author_category_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="no_of_books",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
